import { Decimal } from "@prisma/client/runtime/library";

export const invoiceDetails = [
  {
    sequence: 1,
    invoiceHeaderId: 1,
    serviceId: 1,
    productId: null,
    quantity: 1,
    price: new Decimal(15.0),
    subtotal: new Decimal(15.0),
  },
  {
    sequence: 2,
    invoiceHeaderId: 1,
    serviceId: null,
    productId: 1,
    quantity: 1,
    price: new Decimal(10.0),
    subtotal: new Decimal(10.0),
  },
  {
    sequence: 3,
    invoiceHeaderId: 1,
    serviceId: 2,
    productId: null,
    quantity: 1,
    price: new Decimal(10.0),
    subtotal: new Decimal(10.0),
  },
  {
    sequence: 4,
    invoiceHeaderId: 1,
    serviceId: null,
    productId: 2,
    quantity: 1,
    price: new Decimal(12.99),
    subtotal: new Decimal(12.99),
  },
  {
    sequence: 5,
    invoiceHeaderId: 1,
    serviceId: 3,
    productId: null,
    quantity: 1,
    price: new Decimal(12.0),
    subtotal: new Decimal(12.0),
  },
  // Details for invoice header 2
  {
    sequence: 1,
    invoiceHeaderId: 2,
    serviceId: null,
    productId: 1,
    quantity: 1,
    price: new Decimal(15.99),
    subtotal: new Decimal(15.99),
  },
  {
    sequence: 2,
    invoiceHeaderId: 2,
    serviceId: 4,
    productId: null,
    quantity: 1,
    price: new Decimal(50.0),
    subtotal: new Decimal(50.0),
  },
  {
    sequence: 3,
    invoiceHeaderId: 2,
    serviceId: null,
    productId: 3,
    quantity: 1,
    price: new Decimal(19.99),
    subtotal: new Decimal(19.99),
  },
  {
    sequence: 4,
    invoiceHeaderId: 2,
    serviceId: 5,
    productId: null,
    quantity: 1,
    price: new Decimal(25.0),
    subtotal: new Decimal(25.0),
  },
  {
    sequence: 5,
    invoiceHeaderId: 2,
    serviceId: null,
    productId: 4,
    quantity: 1,
    price: new Decimal(29.99),
    subtotal: new Decimal(29.99),
  },
  // Details for invoice header 3
  {
    sequence: 1,
    invoiceHeaderId: 3,
    serviceId: 3,
    productId: null,
    quantity: 1,
    price: new Decimal(12.0),
    subtotal: new Decimal(12.0),
  },
  {
    sequence: 2,
    invoiceHeaderId: 3,
    serviceId: null,
    productId: 2,
    quantity: 1,
    price: new Decimal(12.99),
    subtotal: new Decimal(12.99),
  },
  {
    sequence: 3,
    invoiceHeaderId: 3,
    serviceId: 1,
    productId: null,
    quantity: 1,
    price: new Decimal(15.0),
    subtotal: new Decimal(15.0),
  },
  {
    sequence: 4,
    invoiceHeaderId: 3,
    serviceId: null,
    productId: 5,
    quantity: 1,
    price: new Decimal(9.99),
    subtotal: new Decimal(9.99),
  },
  {
    sequence: 5,
    invoiceHeaderId: 3,
    serviceId: 4,
    productId: null,
    quantity: 1,
    price: new Decimal(50.0),
    subtotal: new Decimal(50.0),
  },
  // Details for invoice header 4
  {
    sequence: 1,
    invoiceHeaderId: 4,
    serviceId: 4,
    productId: null,
    quantity: 1,
    price: new Decimal(50.0),
    subtotal: new Decimal(50.0),
  },
  {
    sequence: 2,
    invoiceHeaderId: 4,
    serviceId: null,
    productId: 3,
    quantity: 1,
    price: new Decimal(19.99),
    subtotal: new Decimal(19.99),
  },
  {
    sequence: 3,
    invoiceHeaderId: 4,
    serviceId: 2,
    productId: null,
    quantity: 1,
    price: new Decimal(10.0),
    subtotal: new Decimal(10.0),
  },
  {
    sequence: 4,
    invoiceHeaderId: 4,
    serviceId: null,
    productId: 4,
    quantity: 1,
    price: new Decimal(29.99),
    subtotal: new Decimal(29.99),
  },
  {
    sequence: 5,
    invoiceHeaderId: 4,
    serviceId: 1,
    productId: null,
    quantity: 1,
    price: new Decimal(15.0),
    subtotal: new Decimal(15.0),
  },
  // Details for invoice header 5
  {
    sequence: 1,
    invoiceHeaderId: 5,
    serviceId: 5,
    productId: null,
    quantity: 1,
    price: new Decimal(25.0),
    subtotal: new Decimal(25.0),
  },
  {
    sequence: 2,
    invoiceHeaderId: 5,
    serviceId: null,
    productId: 5,
    quantity: 1,
    price: new Decimal(9.99),
    subtotal: new Decimal(9.99),
  },
  {
    sequence: 3,
    invoiceHeaderId: 5,
    serviceId: 3,
    productId: null,
    quantity: 1,
    price: new Decimal(12.0),
    subtotal: new Decimal(12.0),
  },
  {
    sequence: 4,
    invoiceHeaderId: 5,
    serviceId: null,
    productId: 1,
    quantity: 1,
    price: new Decimal(15.99),
    subtotal: new Decimal(15.99),
  },
  {
    sequence: 5,
    invoiceHeaderId: 5,
    serviceId: 2,
    productId: null,
    quantity: 1,
    price: new Decimal(10.0),
    subtotal: new Decimal(10.0),
  },
];
