export const invoiceDetails = [
  {
    sequence: 1,
    invoiceHeaderId: 1,
    serviceId: 1,
    productId: null,
    quantity: 1,
    price: 15.0,
    subtotal: 15.0,
  },
  {
    sequence: 1,
    invoiceHeaderId: 2,
    serviceId: 2,
    productId: null,
    quantity: 1,
    price: 10.0,
    subtotal: 10.0,
  },
  {
    sequence: 1,
    invoiceHeaderId: 3,
    serviceId: 3,
    productId: null,
    quantity: 1,
    price: 12.0,
    subtotal: 12.0,
  },
  {
    sequence: 1,
    invoiceHeaderId: 4,
    serviceId: 4,
    productId: null,
    quantity: 1,
    price: 50.0,
    subtotal: 50.0,
  },
  {
    sequence: 1,
    invoiceHeaderId: 5,
    serviceId: 5,
    productId: null,
    quantity: 1,
    price: 25.0,
    subtotal: 25.0,
  },
];
