export const reservations = [
    {
      date: new Date("2024-06-01T10:00:00.000Z"),
      answer1: "Yes, I have had a haircut here before.",
      answer2: "I prefer morning appointments.",
      answer3: "I want a basic haircut.",
      statusId: 1,
      branchId: 1,
      serviceId: 1,
      userId: 5,
    },
    {
      date: new Date("2024-06-02T11:00:00.000Z"),
      answer1: "No, this is my first time.",
      answer2: "I prefer afternoon appointments.",
      answer3: "I want a clean shave.",
      statusId: 2,
      branchId: 2,
      serviceId: 2,
      userId: 2,
    },
    {
      date: new Date("2024-06-03T12:00:00.000Z"),
      answer1: "Yes, I have had a haircut here before.",
      answer2: "I prefer evening appointments.",
      answer3: "I want a beard trim.",
      statusId: 3,
      branchId: 3,
      serviceId: 3,
      userId: 3,
    },
    {
      date: new Date("2024-06-04T13:00:00.000Z"),
      answer1: "No, this is my first time.",
      answer2: "I prefer morning appointments.",
      answer3: "I want a hair color.",
      statusId: 4,
      branchId: 4,
      serviceId: 4,
      userId: 4,
    },
    {
      date: new Date("2024-06-05T14:00:00.000Z"),
      answer1: "Yes, I have had a haircut here before.",
      answer2: "I prefer afternoon appointments.",
      answer3: "I want a facial.",
      statusId: 5,
      branchId: 5,
      serviceId: 5,
      userId: 5,
    },
  ];
  